version: '3'

services:
  web:
    build: .
    command: bash /app/run_application.sh
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: lesara
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: lesara
    ports:
      - "3306:3306"
